 spring:
   datasource:
     url: jdbc:h2:file:./db/testdb
     driver-class-name: org.h2.Driver
     username: sa
     password:
   jpa:
     hibernate:
       ddl-auto: none
     database-platform: org.hibernate.dialect.H2Dialect
#     properties:
#       hibernate:
#         use_sql_comments: true
#         show_sql: true
#         format_sql: true
   h2:
     console:
       enabled: true

 logging:
   level:
     root: INFO
     com.example.querydsl.demo: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type: TRACE

 #p6spy query logging
 decorator:
   datasource:
     p6spy:
       enable-logging: true